# Generated by Django 3.2.6 on 2021-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipal', '0002_pregunta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='juega',
            name='correcto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='juego',
            name='puntaje',
            field=models.IntegerField(default=0, verbose_name='Puntaje obtenido por el jugador'),
        ),
        migrations.AlterUniqueTogether(
            name='juega',
            unique_together={('idParticipante', 'idJuego', 'idPregunta')},
        ),
    ]
