# Generated by Django 3.2.6 on 2021-09-06 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appPrincipal', '0003_auto_20210901_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juega',
            name='idParticipante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
